dataset:
  train:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: PointM2AE
  init_source: ShapeNet
  base_model: PointM2AE
  drop_path_rate: 0.1
  encoder_depths:
  - 5
  - 5
  - 5
  encoder_dims:
  - 96
  - 192
  - 384
  finetuning_strategy: Full Finetuning
  group_sizes:
  - 16
  - 8
  - 8
  label_smoothing: 0.0
  local_radius:
  - 0.32
  - 0.64
  - 1.28
  num_classes: 7
  num_groups:
  - 512
  - 256
  - 64
  num_heads: 6
  smooth: 0.3
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.05
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
