dataset:
  train:
    _base_: cfgs/dataset/ShapeNetPartsH5.yaml
    others:
      bs: 8
      subset: trainval
      K_FOLDS: 1
  val:
    _base_: cfgs/dataset/ShapeNetPartsH5.yaml
    others:
      bs: 8
      subset: test
      K_FOLDS: 1

grad_norm_clip: 10
max_epoch: 300
npoints: 2048
step_per_update: 1

model:
  NAME: DeepGCN_Seg
  seg_classes: 50
  num_obj_classes: 16
  use_cls_label: False
  channels: 3
  gcn_channels: 64
  k: 9
  n_blocks: 14
  emb_dims: 1024
  c_growth: 64
  conv: edge
  act: relu
  norm: batch
  bias: true
  stochastic: false
  epsilon: 0.2
  knn: matrix
  block_type: res
  use_dilation: true
  dropout: 0.5

optimizer:
  type: AdamW
  kwargs:
    lr: 0.0003
    weight_decay: 0.0001

scheduler:
  type: CosLR
  kwargs:
    initial_epochs: 10
