optimizer:
  type: AdamW
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
scheduler:
  type: CosLR
  kwargs:
    initial_epochs: 10
dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetCV.yaml
    others:
      subset: train
      K_FOLDS: 5
      fold: 0
      bs: 16
  val:
    _base_: cfgs/dataset/TreeDatasetCV.yaml
    others:
      subset: val
      K_FOLDS: 5
      fold: 0
      bs: 16
model:
  NAME: RSCNN
  label_smoothing: 0.0
  num_classes: 7
  input_channels: 3
  relation_prior: 1
  use_xyz: true
  dropout1: 0.5
  dropout2: 0.5
npoints: 1024
step_per_update: 1
max_epoch: 250
grad_norm_clip: 10
