dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
  test:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: test
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: PPFNet
  channels: 3
  dropout1: 0.2
  dropout2: 0.2
  emb_dims: 96
  features:
  - ppf
  - dxyz
  - xyz
  label_smoothing: 0.0
  num_classes: 9
  num_neighbors: 20
  radius: 0.3
npoints: 2048
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
