dataset:
  train:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: DELA
  bn_momentum: 0.1
  bottleneck: 2048
  cor_std:
  - 2.8
  - 5.3
  - 10
  depths:
  - 4
  - 4
  - 4
  dims:
  - 96
  - 192
  - 384
  drop_path: 0.15
  ks:
  - 20
  - 20
  - 20
  label_smoothing: 0.0
  mlp_ratio: 2
  nbr_dims:
  - 48
  - 48
  ns:
  - 1024
  - 256
  - 64
  num_classes: 7
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
