dataset:
  train:
    _base_: cfgs/dataset/ModelNet40Dataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/ModelNet40Dataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: GlobalTransformer
  attn_dropout: 0.0
  channels: 3
  depth: 4
  dim_head: 64
  emb_dims: 1024
  ff_dropout: 0.0
  global_attention: true
  heads: 3
  label_smoothing: 0.0
  num_classes: 40
  patch_dim: 192
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
