optimizer:
  type: AdamW
  part: only_new
  kwargs:
    lr: 0.0005
    weight_decay: 0.05
scheduler:
  type: CosLR
  kwargs:
    initial_epochs: 10
dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetCV.yaml
    others:
      subset: train
      K_FOLDS: 5
      fold: 0
      bs: 16
  val:
    _base_: cfgs/dataset/TreeDatasetCV.yaml
    others:
      subset: val
      K_FOLDS: 5
      fold: 0
      bs: 16
model:
  NAME: VPT_Deep
  init_source: ShapeNet
  base_model: PointMAE
  finetuning_strategy: VPT_Deep
  prompt_nums: 10
  label_smoothing: 0.0
  trans_dim: 384
  depth: 12
  drop_path_rate: 0.1
  cls_dim: 7
  num_heads: 6
  group_size: 32
  num_group: 64
  encoder_dims: 384
npoints: 1024
step_per_update: 1
max_epoch: 250
grad_norm_clip: 10
