dataset:
  train:
    _base_: cfgs/dataset/ModelNet40FewShot.yaml
    others:
      K_FOLDS: 10
      bs: 16
      subset: train
      way: 10
      shot: 10
      fold: 0
  val:
    _base_: cfgs/dataset/ModelNet40FewShot.yaml
    others:
      K_FOLDS: 10
      bs: 16
      subset: test
      way: 10
      shot: 10
      fold: 0
grad_norm_clip: 10
max_epoch: 150
model:
  NAME: CurveNet
  additional_channel: 32
  channels: 3
  dropout: 0.5
  k: 20
  label_smoothing: 0.0
  num_classes: 10
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
