dataset:
  train:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
  test:
    _base_: cfgs/dataset/TreeDatasetHELIALS.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: test
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: IDPT
  init_source: HELIALS
  base_model: PointMAE
  cls_dim: 9
  cls_type: all
  depth: 12
  drop_path_rate: 0.1
  encoder_dims: 384
  finetuning_strategy: IDPT
  group_size: 32
  label_smoothing: 0.0
  num_group: 64
  num_heads: 6
  prompt_layer: 11
  prompt_module: dgcnn
  trans_dim: 384
npoints: 2048
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.05
  type: AdamW
  part: only_new
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
