dataset:
  train:
    _base_: cfgs/dataset/WHUUrban3DDataset.yaml
    others:
      bs: 8
      subset: train
      test_area: 5
      feature_mode: xyzi
      K_FOLDS: 1
  val:
    _base_: cfgs/dataset/WHUUrban3DDataset.yaml
    others:
      bs: 8
      subset: val
      test_area: 5
      K_FOLDS: 1

grad_norm_clip: 10
max_epoch: 100  # FIXME -> only for debuggign 100
npoints: 200000
step_per_update: 1

model:
  NAME: PointTransformerV3_Seg
  input_channels: 4
  channels: 4
  seg_classes: 2
  num_obj_classes: 1
  use_cls_label: False
  dropout: 0.3
  enable_flash: false

optimizer:
  type: AdamW
  kwargs:
    lr: 0.005  # 0.0003
    weight_decay: 0.0001

scheduler:
  type: CosLR  # LambdaLR  # CosLR  # StepLR
  kwargs:
    initial_epochs: 3
