dataset:
  train:
    _base_: cfgs/dataset/ModelNet40FewShot.yaml
    others:
      K_FOLDS: 10
      bs: 16
      subset: train
      way: 5
      shot: 20
      fold: 0
  val:
    _base_: cfgs/dataset/ModelNet40FewShot.yaml
    others:
      K_FOLDS: 10
      bs: 16
      subset: test
      way: 5
      shot: 20
      fold: 0
grad_norm_clip: 10
max_epoch: 150
model:
  NAME: PointConv
  bandwidth1: 0.1
  bandwidth2: 0.2
  bandwidth3: 0.4
  channels_input: 3
  dropout: 0.7
  label_smoothing: 0.0
  npoint1: 512
  npoint2: 128
  nsample1: 32
  nsample2: 64
  num_classes: 5
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
