dataset:
  train:
    _base_: cfgs/dataset/ShapeNetPartsH5.yaml
    others:
      bs: 8
      subset: trainval
      K_FOLDS: 1
  val:
    _base_: cfgs/dataset/ShapeNetPartsH5.yaml
    others:
      bs: 8
      subset: test
      K_FOLDS: 1

grad_norm_clip: 10
max_epoch: 300
npoints: 2048
step_per_update: 1

model:
  NAME: PointTransformerV2_Seg
  channels: 3
  seg_classes: 50
  num_obj_classes: 16
  use_cls_label: False
  grid_sizes: [0.06, 0.15, 0.375, 0.9375]

optimizer:
  type: AdamW
  kwargs:
    lr: 0.0003
    weight_decay: 0.0001

scheduler:
  type: CosLR
  kwargs:
    initial_epochs: 10
