dataset:
  train:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: train
  val:
    _base_: cfgs/dataset/TreeDataset.yaml
    others:
      K_FOLDS: 1
      bs: 16
      subset: val
grad_norm_clip: 10
max_epoch: 250
model:
  NAME: PointSCNet
  channels: 3
  dropout1: 0.4
  dropout2: 0.5
  label_smoothing: 0.0
  normal_channel: false
  num_classes: 7
npoints: 1024
optimizer:
  kwargs:
    lr: 0.0005
    weight_decay: 0.0001
  type: AdamW
scheduler:
  kwargs:
    initial_epochs: 10
  type: CosLR
step_per_update: 1
